### ISSUE TITLE
Test GraalVM 20 dev build

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#258]
See https://github.com/graalvm/graalvm-ce-dev-builds/releases

- [x] verify if things still work with jdk8 (mac, linux and windows)

- [x] is this fixed for jdk11? https://github.com/oracle/graal/issues/2015#issuecomment-575268745

- [x] is this fixed for windows? https://github.com/oracle/graal/issues/1876

- [x] windows build (without 1784 and 1876) graalvm 20 jdk11 works, see branch `windows-graalvm20-jdk11`) 

- [ ] is this fixed for windows? https://github.com/oracle/graal/issues/1784
not yet: https://github.com/oracle/graal/issues/1784#issuecomment-583767384

- [ ] is there a fix for dealing with javax.xml? https://github.com/oracle/graal/issues/1387

**Comment by FieryCod** [comment]
@borkdude did you check whether graal#1387 is fixed? That's the only reason I stopped developing holy-lambda.

**Comment by borkdude** [comment]
I know as much about graal#1387 as you do :). Might be good poking the devs on the graal slack about it.
